package org.hdivsamples.verticle;

public enum Functions {

	// @formatter:off
	FIND_ACCOUNTS_BY_USERNAME_AND_PASSWORD,
	FIND_ACCOUNTS_BY_USERNAME,
	FIND_ACCOUNTS,
	FIND_CASH_ACCOUNTS_BY_USERNAME,
	FIND_CREDIT_ACCOUNTS_BY_USERNAME,
	EXISTS_STORAGE,
	LOAD_STORAGE,
	SAVE_STORAGE,
	FIND_TRANSACTIONS_BY_CASH_ACCOUNT_NUMBER,
	CREATE_NEW_TRANSFER
	// @formatter:on
}
